version: '2'
services:
  vault:
    image: vault
    container_name: vault-dev
    ports:
      - "8200:8200"
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: "s3cret"
      VAULT_ADDR: "http://0.0.0.0:8200"
    entrypoint: vault server --dev #-config=/vault/config/vault.json